-- Philamentix Hub V18.5 – kompakte Systemstatus-Historie
-- Einmal vollständig im Supabase SQL Editor ausführen.

begin;

create table if not exists public.system_health_samples (
  id bigint generated by default as identity primary key,
  service_id text not null,
  level text not null,
  latency_ms integer null,
  message text not null default '',
  checked_at timestamptz not null default now(),
  constraint system_health_samples_level_check check (level in ('ok','warning','error'))
);

create index if not exists system_health_samples_checked_at_idx
  on public.system_health_samples (checked_at desc);
create index if not exists system_health_samples_service_idx
  on public.system_health_samples (service_id, checked_at desc);

alter table public.system_health_samples enable row level security;
revoke all on table public.system_health_samples from anon, authenticated;
grant all on table public.system_health_samples to service_role;

commit;
